# PlatformIoPublish.yml
# Github workflow script to publish a release to PlatformIo.
#
# Copyright (C) 2021-2022  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: PlatformIo publishing
on:
  workflow_dispatch: # To run it manually
    description: manual PlatformIo publishing
  release: # see: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build and publish
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_TOKEN }}
      run: |
        pio package publish --owner arminjo --non-interactive
#      run: |
#        pio package pack
#        pio package publish --owner arminjo --non-interactive
        